spring:
  profiles:
    active: prod
---

server: 
 port: 5001
spring: 
 profiles: dev
 application: 
  name: microservice-config-client
eureka:   
  client: 
    service-url: 
      defaultZone: http://eureka-dev:7003/eureka/
---

server: 
 port: 5002
spring: 
 profiles: prod
 application: 
  name: microservice-config-client
eureka:   
  client: 
    service-url: 
      defaultZone: http://eureka-dev:7003/eureka/
