spring:
  profiles:
    active: prod
---

server: 
 portal: 5001
spring: 
 profiles: dev
 application: 
  name: microservice-config-client
eureka: 
  client: 
   service-url: 
    defaultZone: http://eureka-dev:7003/eureka/


---

server: 
 portal: 5002
spring: 
 profiles: prod
 application: 
  name: microservice-config-client
eureka: 
  client: 
   service-url: 
    defaultZone: http://eureka-prod:7003/eureka/